### ISSUE TITLE
Context cannot be encoded.

### ISSUE THREAD

**Issue by BrooklinJazz** [BrooklinJazz/kino_tailwind_playground#1]
Encoding the context in our attrs causes a protocol encoding error.

```elixir
  def to_attrs(ctx) do
    %{"source" => ctx.assigns.source, "ctx" => ctx}
  end
```

This causes the following Protocol encoding error, 

13:52:27.174 [error] Task #PID<0.639.0> started from #PID<0.585.0> terminating
** (Protocol.UndefinedError) protocol Jason.Encoder not implemented for %{__private__: %{client_ids_with_pid: %{"sqigph6rq7kkshqxbgduj6uqbjppfilf" => #PID<0.632.0>}, monitors_with_client_id: %{#Reference<26505.2126526964.3632791554.219065> => "sqigph6rq7kkshqxbgduj6uqbjppfilf"}, ref: "fvo5zoh4dqfocgq3x72xd52rvsxeueii"}, __struct__: Kino.JS.Live.Context, assigns: %{source: ""}, origin: nil} of type Kino.JS.Live.Context (a struct), Jason.Encoder protocol must always be explicitly implemented.

If you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:

@derive {Jason.Encoder, only: [....]}
defstruct ...

It is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:

@derive Jason.Encoder
defstruct ...

Finally, if you don't own the struct you want to encode to JSON, you may use Protocol.derive/3 placed outside of any module:

Protocol.derive(Jason.Encoder, NameOfTheStruct, only: [...])
Protocol.derive(Jason.Encoder, NameOfTheStruct)
. This protocol is implemented for the following type(s): Any, Atom, BitString, Date, DateTime, Decimal, Ecto.Association.NotLoaded, Ecto.Schema.Metadata, Float, Integer, Jason.Fragment, Jason.OrderedObject, List, Map, NaiveDateTime, Time
(jason 1.4.0) lib/jason.ex:164: Jason.encode!/2
(livebook 0.8.1) lib/livebook/live_markdown/export.ex:235: Livebook.LiveMarkdown.Export.render_metadata/1
(livebook 0.8.1) lib/livebook/live_markdown/export.ex:242: Livebook.LiveMarkdown.Export.prepend_metadata/2
(livebook 0.8.1) lib/livebook/live_markdown/export.ex:90: anonymous fn/3 in Livebook.LiveMarkdown.Export.render_section/3
(elixir 1.14.2) lib/enum.ex:1780: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
(elixir 1.14.2) lib/enum.ex:1780: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
(livebook 0.8.1) lib/livebook/live_markdown/export.ex:82: Livebook.LiveMarkdown.Export.render_section/3
(elixir 1.14.2) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
Function: #Function<22.43197936/0 in Livebook.Session.maybe_save_notebook_async/1>
Args: []

To resolve this issue, we need another way of accessing the editor `code` attr. Unfortunately we only have access to it in the to_source callback.
    
 ```elixir
def to_source(attrs) do
  broadcast_event(attrs["ctx"], "display-html", %{"html" => attrs["html"]})
  # we arent' rendering anything for now.
  "Kino.nothing()"
end
 ```
    
We think we need to ask the Kino team how we can access the code editor contents or broadcast a message without the full ctx.

**Comment by BrooklinJazz** [comment]
Resolved by sending the smart cell a message to itself
